import type { Metadata } from 'next';
import './globals.css';
import '@/styles/utilities.css';
import Providers from '@/components/Providers/Providers';
import '@/styles/fonts.css';
import { Toaster } from 'sonner';
import styles from './layout.module.scss';
import clsx from 'clsx';
import ScrollToTop from '@/components/ScrollToTop/ScrollToTop';

export const metadata: Metadata = {
  title: 'Brain Flip',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light" data-theme="light">
      <body>
        <div id="header-portal" className={clsx(styles.headerPortal)}></div>
        <div
          id="header-secondary-portal"
          className={clsx(styles.headerSecondary)}
        ></div>
        <Toaster richColors position="top-center" />
        <div
          id="scroll-to-top-portal"
          className={clsx(styles.scrollToTop)}
        ></div>
        <ScrollToTop />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
