// File: app/layout.tsx
import { ClientWrapper } from '@/components/ClientWrapper/ClientWrapper';
import { Sidebar } from '@/components/Sidebar/Sidebar';
import { SidebarProvider } from '@/components/Sidebar/SidebarContext';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Laklu Res',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SidebarProvider>
          <div className="flex">
            <Sidebar />
            <ClientWrapper>{children}</ClientWrapper>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
