import { MobileSidebar } from '@/components/Sidebar/MobileSidebar';
import { Sidebar } from '@/components/Sidebar/Sidebar';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Brain Flip',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <Sidebar />

          <main className=" p-4">{children}</main>
        </div>
      </body>
    </html>
  );
}
