name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to VPS and Build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Kiểm tra và cài đặt Node.js 18 nếu cần
            if ! command -v node &> /dev/null || [ $(node -v | cut -d. -f1 | tr -d 'v') -lt 18 ]; then
              echo "Cài đặt Node.js 18..."
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
            
            # Kiểm tra phiên bản Node.js
            node -v
            npm -v
            
            # Tạo thư mục tạm để build
            rm -rf /var/www/cmslaklu-temp || true
            mkdir -p /var/www/cmslaklu-temp
            cd /var/www/cmslaklu-temp
            
            # Clone repository với xác thực
            git clone https://oauth2:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.GH_USERNAME }}/${{ secrets.GH_REPO }}.git .
            
            # Cài đặt dependencies với flag legacy-peer-deps
            npm install --legacy-peer-deps
            
            # Thiết lập các biến môi trường
            echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" > .env.local
            echo "NEXT_PUBLIC_SERVER_URL=${{ secrets.NEXT_PUBLIC_SERVER_URL }}" >> .env.local
            
            # Build project
            npm run build --no-lint
            
            # Nếu build thành công, cập nhật thư mục chính
            if [ $? -eq 0 ]; then
              # Backup thư mục cũ nếu có
              if [ -d "/var/www/cmslaklu" ]; then
                rm -rf /var/www/cmslaklu-backup || true
                mv /var/www/cmslaklu /var/www/cmslaklu-backup
              fi
              
              # Di chuyển thư mục mới vào vị trí
              mv /var/www/cmslaklu-temp /var/www/cmslaklu
              
              # Đảm bảo PM2 đã được cài đặt
              if ! command -v pm2 &> /dev/null; then
                sudo npm install -g pm2
              fi
              
              # Khởi động lại ứng dụng
              cd /var/www/cmslaklu
              pm2 restart cmslaklu || pm2 start ecosystem.config.js
              
              echo "Deployment successful!"
            else
              echo "Build failed, deployment aborted!"
              exit 1
            fi 